version: '3.4'

services:
  webui:
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "SpaBaseUrl=http://clientapp:4200"
    container_name: "BankWebUI"

  clientapp:
    container_name: "BankClientApp"
    image: ${DOCKER_REGISTRY-}clientapp
    build:
      context: ./src/WebUI/ClientApp
      dockerfile: Dockerfile
    depends_on:
      - webui
    restart: on-failure

  db:
    container_name: "BankSQLServer"
    ports:
      - "1433:1433"